steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/flux3d:${SHORT_SHA}", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/flux3d:${SHORT_SHA}"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/flux3d:${SHORT_SHA}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

substitutions:
  _REGION: us-central1
  _REPO: flux3d
  _SERVICE: flux3d-engine

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/flux3d:${SHORT_SHA}"
